"""Build a one-page PDF report from an analysis file and the agent's text.

The agent writes only what needs judgment (title, summary, recommendations) as JSON:
    {"title": "...", "question": "...", "summary": "...", "recommendations": ["...", "..."]}

Everything factual is generated from the analysis: the chart, the metrics table and the
"Method & limitations" block (articles, period, filters, exclusions, proxies, missing
languages, confidence reasons). Numbers in the agent's text are checked against the analysis.
"""

import json
import re
import tempfile
from datetime import date
from pathlib import Path

import matplotlib
from fpdf import FPDF, XPos, YPos
from fpdf.fonts import FontFace

from .chart import CONFIDENCE, INK, INK_2, MUTED, load_analysis, trend_chart

FONT_DIR = Path(matplotlib.get_data_path()) / "fonts" / "ttf"  # DejaVu ships with matplotlib
LIMITS = {"title": 100, "question": 250, "summary": 900, "recommendation": 300, "recommendations": 5}

T = {
    "en": {
        "meta": "Topic: {label} (Wikidata {qid}) · Languages: {langs} · Period: {start} – {end} · Generated {today}",
        "question": "Question", "recommendations": "Recommendations", "method": "Method & limitations",
        "cols": ["Lang", "Article", "Views/day", "Per million", "Share change", "Raw change", "Months up",
                 "Trend", "Confidence"],
        "trend": {"rising": "rising", "falling": "falling", "flat": "flat", "mixed": "mixed", "unknown": "unknown"},
        "data": "Data: Wikimedia Pageviews API, daily views by humans (agent=user, all access methods), "
                "{start} – {end}. Views of redirects are added to each article.",
        "share": "Share of attention = views per million pageviews of the same language edition. It corrects for "
                 "editions of different size and for the overall decline of Wikipedia traffic.",
        "change": "Change compares the last {k} months with the same months a year earlier, so seasonality cancels "
                  "out. Single-day spikes are removed.",
        "change_short": "Only {n} months of data: change compares the last {k} months with the {k} before them; "
                        "seasonality is NOT controlled.",
        "excluded": "Excluded as anomalous (whole month far above its year, with its pair a year apart): {items}.",
        "articles": "Articles: {items}.", "proxy": "proxy approved by the user",
        "missing": "No data: {items}.",
        "confidence": "Confidence: {items}.",
        "caveat": "Pageviews show curiosity, not willingness to pay: use them to choose what to validate next, "
                  "not as a demand forecast.",
        "footer": "Generated by the wiki-interest skill · Data: Wikimedia Foundation pageviews (CC0)",
    },
    "uk": {
        "meta": "Тема: {label} (Wikidata {qid}) · Мови: {langs} · Період: {start} – {end} · Створено {today}",
        "question": "Питання", "recommendations": "Рекомендації", "method": "Методологія та обмеження",
        "cols": ["Мова", "Стаття", "На день", "На млн", "Зміна частки", "Зміна абс.", "Міс. вище",
                 "Тренд", "Довіра"],
        "reasons": {
            "very_low_volume": "дуже малий обсяг ({views_per_day} перегл./день)",
            "low_volume": "малий обсяг ({views_per_day} перегл./день)",
            "short_period": "лише {months} міс. даних",
            "few_comparable_months": "лише {months} міс. можна порівняти з торішніми",
            "new_article": "статті, імовірно, ще не було перші {days} дн.",
            "proxy": "замінник замість точного поняття",
            "spikes": "{share:.0%} переглядів припадає на сплески",
            "automated": "{share:.0%} трафіку автоматизований",
            "inconsistent": "зміна неоднорідна: лише {months_up} з {months} міс. вищі за торішні",
            "solid": "достатній обсяг, два повні роки, стабільна зміна",
        },
        "trend": {"rising": "зростає", "falling": "падає", "flat": "стабільно", "mixed": "неоднозначно",
                  "unknown": "невідомо"},
        "data": "Дані: Wikimedia Pageviews API, денні перегляди людьми (agent=user, усі способи доступу), "
                "{start} – {end}. Перегляди редиректів додано до статей.",
        "share": "Частка уваги = переглядів на мільйон переглядів того самого мовного розділу. Це враховує різний "
                 "розмір розділів і загальне падіння трафіку Вікіпедії.",
        "change": "Зміна порівнює останні {k} міс. з тими самими місяцями роком раніше, тому сезонність "
                  "скорочується. Одноденні сплески прибрано.",
        "change_short": "Лише {n} міс. даних: зміна порівнює останні {k} міс. з {k} попередніми; сезонність "
                        "НЕ враховано.",
        "excluded": "Виключено як аномальні (увесь місяць значно вищий за рік, разом із парою роком раніше): {items}.",
        "articles": "Статті: {items}.", "proxy": "замінник, погоджений користувачем",
        "missing": "Немає даних: {items}.",
        "confidence": "Довіра: {items}.",
        "caveat": "Перегляди показують цікавість, а не готовність платити: це сигнал, що перевіряти далі, "
                  "а не прогноз попиту.",
        "footer": "Створено навичкою wiki-interest · Дані: перегляди Wikimedia Foundation (CC0)",
    },
}


# --- Content validation & number check -------------------------------------------------------

def load_content(source):
    text = Path(source).read_text() if source != "-" else __import__("sys").stdin.read()
    try:
        content = json.loads(text)
    except ValueError as e:
        raise ValueError(f"Content is not valid JSON: {e}") from None
    errors = []
    for key in ("title", "summary"):
        if not str(content.get(key, "")).strip():
            errors.append(f"'{key}' is required")
    recs = content.get("recommendations") or []
    if not isinstance(recs, list) or not recs:
        errors.append("'recommendations' must be a non-empty list of strings")
    for key in ("title", "question", "summary"):
        if len(str(content.get(key, ""))) > LIMITS[key]:
            errors.append(f"'{key}' is longer than {LIMITS[key]} characters")
    if isinstance(recs, list):
        if len(recs) > LIMITS["recommendations"]:
            errors.append(f"at most {LIMITS['recommendations']} recommendations")
        errors += [f"recommendation {i + 1} is longer than {LIMITS['recommendation']} characters"
                   for i, r in enumerate(recs) if len(str(r)) > LIMITS["recommendation"]]
    if errors:
        raise ValueError("Invalid report content: " + "; ".join(errors))
    return content


NUMBER_RE = re.compile(r"[-+−]?\d{1,3}(?:[   ]\d{3})+(?:[.,]\d+)?|[-+−]?\d+(?:[.,]\d+)?")
DATE_RE = re.compile(r"\b\d{4}(?:[-–./]\d{1,2}){0,2}\b")


def _parse_number(token):
    t = token.replace("−", "-").replace(" ", "").replace(" ", "")
    t = re.sub(r"(?<=\d) (?=\d{3})", "", t)
    if re.fullmatch(r"-?\+?\d+,\d{3}", t):  # English thousands separator
        t = t.replace(",", "")
    return abs(float(t.replace(",", ".").replace("+", "")))


def allowed_numbers(analysis):
    """Every number the agent may legitimately quote, in the forms it may appear."""
    values = set()

    def walk(x, key=""):
        if isinstance(x, bool):
            return
        if isinstance(x, (int, float)):
            values.add(abs(x))
            if abs(x) <= 10 and key not in ("peak_index", "ratio", "typical_views"):
                values.add(abs(x) * 100)  # ratios quoted as percentages
        elif isinstance(x, dict):
            for k, v in x.items():
                walk(v, k)
        elif isinstance(x, list):
            for v in x:
                walk(v, key)

    walk(analysis["results"])
    walk(analysis["period"])
    values.update(range(0, 6))  # small counts: number of languages, recommendations, years
    return values


def unverified_numbers(texts, analysis):
    allowed = allowed_numbers(analysis)
    bad = []
    for text in texts:
        for token in NUMBER_RE.findall(DATE_RE.sub(" ", text)):
            n = _parse_number(token)
            decimals = len(re.split(r"[.,]", token)[1]) if re.search(r"[.,]\d{1,2}$", token) else 0
            tol = 0.5 * 10 ** -decimals + 1e-9
            if not any(abs(n - a) <= tol for a in allowed):
                bad.append(token.strip())
    return sorted(set(bad), key=bad.index)


# --- PDF ---------------------------------------------------------------------------------------

def _hex(c):
    return tuple(int(c[i:i + 2], 16) for i in (1, 3, 5))


def _pct(x):
    return "–" if x is None else f"{x * 100:+.1f}%"


def method_lines(a, lang):
    t = T[lang]
    p = a["period"]
    results = a["results"]
    first = next(iter(results.values()))
    g = first["growth"]
    lines = [t["data"].format(start=p["start"], end=p["end"]), t["share"]]
    if g["seasonality_controlled"]:
        lines.append(t["change"].format(k=g["window_months"]))
    else:
        lines.append(t["change_short"].format(n=len(a["monthly"][next(iter(results))]["months"]),
                                              k=g["window_months"]))
    excluded = [f"{l} {m}" for l, r in results.items() for m in r["growth"]["excluded_months"]]
    if excluded:
        lines.append(t["excluded"].format(items=", ".join(excluded)))
    arts = [f"{l} – {r['title']}" + (f" ({t['proxy']})" if r["proxy"] else "") for l, r in results.items()]
    lines.append(t["articles"].format(items="; ".join(arts)))
    if a["missing"]:
        lines.append(t["missing"].format(items="; ".join(f"{l} – {why}" for l, why in a["missing"].items())))
    def reasons(conf):
        texts = t.get("reasons")
        if not texts:
            return conf["reasons"]
        return [texts[c["code"]].format(**c) for c in conf.get("reason_codes", [])] or conf["reasons"]

    conf = [f"{l} {CONFIDENCE.get(lang, {}).get(r['confidence']['level'], r['confidence']['level'])} "
            f"({'; '.join(reasons(r['confidence']))})" for l, r in results.items()]
    lines.append(t["confidence"].format(items="; ".join(conf)))
    lines.append(t["caveat"])
    return lines


class Report(FPDF):
    def __init__(self, footer_text):
        super().__init__(format="A4")
        self.footer_text = footer_text
        self.set_margins(14, 12, 14)
        self.set_auto_page_break(True, margin=12)
        self.add_font("DejaVu", "", FONT_DIR / "DejaVuSans.ttf")
        self.add_font("DejaVu", "B", FONT_DIR / "DejaVuSans-Bold.ttf")
        self.add_font("DejaVu", "I", FONT_DIR / "DejaVuSans-Oblique.ttf")

    def footer(self):
        self.set_y(-9)
        self.set_font("DejaVu", "", 6.5)
        self.set_text_color(*_hex(MUTED))
        self.cell(0, 4, self.footer_text, align="L")

    def heading(self, text):
        self.ln(2)
        self.set_font("DejaVu", "B", 9.5)
        self.set_text_color(*_hex(INK))
        self.cell(0, 5, text, new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    def para(self, text, size=9, color=INK, style="", h=4.4):
        self.set_font("DejaVu", style, size)
        self.set_text_color(*_hex(color))
        self.multi_cell(0, h, text, align="L", new_x=XPos.LMARGIN, new_y=YPos.NEXT)


def build_pdf(a, content, lang, out_path, chart_path):
    t = T[lang]
    pdf = Report(t["footer"])
    pdf.add_page()
    width = pdf.w - pdf.l_margin - pdf.r_margin

    pdf.para(content["title"], size=15, style="B", h=7)
    p = a["period"]
    pdf.para(t["meta"].format(label=a["topic"]["label"] or "–", qid=a["topic"]["qid"] or "–",
                              langs=", ".join(list(a["results"]) + list(a["missing"])),
                              start=p["start"][:7], end=p["end"][:7], today=date.today().isoformat()),
             size=7.5, color=INK_2, h=4)
    if content.get("question"):
        pdf.ln(1)
        pdf.para(f"{t['question']}: {content['question']}", size=8.5, color=INK_2, style="I")
    pdf.ln(2)
    pdf.para(content["summary"], size=9.5, h=4.8)

    pdf.ln(2)
    pdf.image(str(chart_path), w=width)

    # Metrics table (also the accessible "table view" of the chart).
    pdf.ln(1)
    pdf.set_font("DejaVu", "", 7.5)
    pdf.set_text_color(*_hex(INK))
    head = FontFace(emphasis="BOLD", color=_hex(INK), fill_color=(240, 239, 236))
    with pdf.table(col_widths=(10, 38, 15, 15, 17, 15, 14, 17, 17), line_height=4.2, headings_style=head,
                   borders_layout="HORIZONTAL_LINES", text_align=("LEFT", "LEFT", "RIGHT", "RIGHT", "RIGHT",
                                                                  "RIGHT", "RIGHT", "LEFT", "LEFT")) as table:
        table.row(t["cols"])
        for l, r in a["results"].items():
            c = r["consistency"]
            row = table.row()
            row.cell(l)
            row.cell(r["title"] + (" *" if r["proxy"] else ""), link=r["url"])
            row.cell(f"{r['avg_daily_views']:.1f}")
            row.cell(f"{r['share_per_million']:.1f}")
            row.cell(_pct(r["growth"]["normalized"]))
            row.cell(_pct(r["growth"]["raw"]))
            row.cell("–" if c["months_up"] is None else f"{c['months_up']}/{c['months_compared']}")
            row.cell(t["trend"].get(r["trend"], r["trend"]))
            row.cell(CONFIDENCE.get(lang, {}).get(r["confidence"]["level"], r["confidence"]["level"]))

    pdf.heading(t["recommendations"])
    for rec in content["recommendations"]:
        pdf.set_font("DejaVu", "", 9)
        pdf.set_text_color(*_hex(INK))
        pdf.cell(4, 4.6, "•")
        pdf.multi_cell(width - 4, 4.6, rec, align="L", new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    pdf.heading(t["method"])
    for line in method_lines(a, lang):
        pdf.para(line, size=7, color=INK_2, h=3.4)

    pages = pdf.page_no()
    pdf.output(str(out_path))
    return pages


def report(analysis_path, content_source, lang="en", out_path=None):
    path = Path(analysis_path)
    a = load_analysis(path)
    content = load_content(content_source)
    lang = lang if lang in T else "en"
    out_path = Path(out_path) if out_path else path.with_name(path.name.removesuffix(".analysis.json") + ".report.pdf")

    with tempfile.TemporaryDirectory() as tmp:
        chart_path = trend_chart(a, Path(tmp) / "trend.png", lang, width_mm=182, height_mm=66)
        pages = build_pdf(a, content, lang, out_path, chart_path)

    if pages > 1:
        out_path.unlink(missing_ok=True)
        return {"status": "error", "error": f"Report does not fit on one page ({pages} pages).",
                "agent_hint": "Shorten 'summary' and 'recommendations' (fewer, shorter items) and rerun."}

    texts = [content["title"], content.get("question", ""), content["summary"], *content["recommendations"]]
    bad = unverified_numbers([x for x in texts if x], a)
    hints = []
    if bad:
        hints.append(f"These numbers in your text are not in the analysis: {', '.join(bad)}. "
                     "Replace them with numbers from 'facts' or remove them, then rerun report.")
    hints.append("Share the PDF path with the user.")
    return {"status": "ok" if not bad else "needs_review", "pdf": str(out_path), "pages": pages,
            "unverified_numbers": bad, "agent_hint": " ".join(hints)}
